### ISSUE TITLE
Introspecting access token no longer works in 5.2.0-rc.1

### ISSUE THREAD

**Issue by pim-nijssen** [reinkrul/java-nuts-client#5]
Since version 5.2.0-rc.1, the `introspectAccessToken` function in the `AuthApi` class no longer works. The introspection always returns
```
{
    "active": false
}
```
According to the nuts node logs, this is caused by `Missing token for introspection`. After checking the generated `AuthApi` class, it turns out that the token is indeed not added to the request as form data. Further investigation showed that this was caused by changing the `library` in the `configOptions` of the OpenAPI generator to `native`.
I tried changing this back to default (which uses okhttp3) and regenerate the client but this caused problems with missing dependencies.

**Comment by reinkrul** [comment]
Thanks for reporting this 👍 , I'll look into it this weekend

**Comment by reinkrul** [comment]
Caused by bug in OpenAPI Generator Tools I updated to. I released v5.3.0-rc.1 (https://github.com/reinkrul/java-nuts-client/commit/0befa9ac394c1b9bab44d4636ad312dd8bb5e0d4), which should fix the issue and updates to the latest Nuts API.

Should be synced to Maven Central within 24h. Can you test it and let me know if the new version works in your case?

**Comment by pim-nijssen** [comment]
We checked and tested the new version and the problem appears to be resolved. Thank you for the quick response.
